### ISSUE TITLE
File:// doesn't work on CentOS7 - Defaults to git clone

### ISSUE THREAD

**Issue by din-eshch** [dxa4481/truffleHog#127]
Trying to run "trufflehog --regex --entropy=True file://tmp/tmp-con/" on Mac works fine but fails on CentOS 7. It ignores "file:" and defaults to git clone. 

trufflehog --regex --entropy=True file://tmp/tmp-con/
Traceback (most recent call last):
  File "/usr/bin/trufflehog", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/truffleHog/truffleHog.py", line 51, in main
    output = find_strings(args.git_url, args.since_commit, args.max_depth, args.output_json, args.do_regex, do_entropy, surpress_output=False)
  File "/usr/lib/python2.7/site-packages/truffleHog/truffleHog.py", line 245, in find_strings
    project_path = clone_git_repo(git_url)
  File "/usr/lib/python2.7/site-packages/truffleHog/truffleHog.py", line 120, in clone_git_repo
    Repo.clone_from(git_url, project_path)
  File "/usr/lib/python2.7/site-packages/git/repo/base.py", line 925, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, **kwargs)
  File "/usr/lib/python2.7/site-packages/git/repo/base.py", line 880, in _clone
    finalize_process(proc, stderr=stderr)
  File "/usr/lib/python2.7/site-packages/git/util.py", line 341, in finalize_process
    proc.wait(**kwargs)
  File "/usr/lib/python2.7/site-packages/git/cmd.py", line 291, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v file://tmp/tmp-con/ /tmp/tmp761PvK
  stderr: 'fatal: '/tmp-con/' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by dxa4481** [comment]
Add an extra slash `file:///`

**Comment by din-eshch** [comment]
Same error after running [root /tmp/tmp-con] UNKNOWN_NODE_NAME $ 
*trufflehog --regex --entropy=True file:///tmp/tmp-con/*
Traceback (most recent call last):
  File "/usr/bin/trufflehog", line 11, in <module>
    sys.exit(main())

**Comment by dxa4481** [comment]
Can you post the entire stack trace when you run it with 3 slashes?

**Comment by din-eshch** [comment]
Here you go

[root@ /tmp/tmp-con] UNKNOWN_NODE_NAME $ trufflehog --regex --entropy=True file:///tmp/tmp-con/
Traceback (most recent call last):
  File "/usr/bin/trufflehog", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/truffleHog/truffleHog.py", line 51, in main
    output = find_strings(args.git_url, args.since_commit, args.max_depth, args.output_json, args.do_regex, do_entropy, surpress_output=False)
  File "/usr/lib/python2.7/site-packages/truffleHog/truffleHog.py", line 245, in find_strings
    project_path = clone_git_repo(git_url)
  File "/usr/lib/python2.7/site-packages/truffleHog/truffleHog.py", line 120, in clone_git_repo
    Repo.clone_from(git_url, project_path)
  File "/usr/lib/python2.7/site-packages/git/repo/base.py", line 925, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, **kwargs)
  File "/usr/lib/python2.7/site-packages/git/repo/base.py", line 874, in _clone
    v=True, **add_progress(kwargs, git, progress))
  File "/usr/lib/python2.7/site-packages/git/cmd.py", line 424, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/git/cmd.py", line 873, in _call_process
    return self.execute(call, **_kwargs)
  File "/usr/lib/python2.7/site-packages/git/cmd.py", line 601, in execute
    raise GitCommandNotFound(command, err)
git.exc.GitCommandNotFound: Cmd('git') not found due to: OSError('[Errno 2] No such file or directory')
  cmdline: git clone -v file:///tmp/tmp-con/ /tmp/tmpmzCfHw
[root@ /tmp/tmp-con] UNKNOWN_NODE_NAME $

**Comment by dxa4481** [comment]
So  based on `git.exc.GitCommandNotFound: Cmd('git') not found due to: OSError('[Errno 2] No such file or directory')`

It looks like you don't have git installed on the system

**Comment by din-eshch** [comment]
Works fine now. I did not realize *git* is required to run trufflehog on a local folder. Thanks
