### ISSUE TITLE
Doesn't prompt for authentication for private GitHub repo

### ISSUE THREAD

**Issue by mcmahonjohn** [dxa4481/truffleHog#31]
I have a private repo I tried this against and I never was prompted to provide a username/password. Though, I do have SSH setup as well I don't think it checks for that.

```
C:\Users\MyName\Desktop\GitHub\truffleHog> python truffleHog.py https://github.com/mcmahonjohn/private-repo
Traceback (most recent call last):
  File "truffleHog.py", line 130, in <module>
    project_path = find_strings(args.git_url)
  File "truffleHog.py", line 67, in find_strings
    Repo.clone_from(git_url, project_path)
  File "C:\Python\Python27\lib\site-packages\git\repo\base.py", line 925, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, **kwargs)
  File "C:\Python\Python27\lib\site-packages\git\repo\base.py", line 880, in _clone
    finalize_process(proc, stderr=stderr)
  File "C:\Python\Python27\lib\site-packages\git\util.py", line 341, in finalize_process
    proc.wait(**kwargs)
  File "C:\Python\Python27\lib\site-packages\git\cmd.py", line 291, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v https://github.com/mcmahonjohn/private c:\users\MyName\appdata\local\temp\tmpmtcgg4
  stderr: 'Cloning into 'c:\users\MyName\appdata\local\temp\tmpmtcgg4'...
bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': Invalid argument
'
```

**Comment by AntonKuzminRussia** [comment]
I think username and password in URL may help you. 
python truffleHog.py https://username:password@github.com/....

**Comment by dxa4481** [comment]
Try either using SSH, or just clone the repo and run it locally with file:///

**Comment by gs-akmondal** [comment]
does this work for private repositories?

**Comment by dxa4481** [comment]
It does. Use SSH authentication, or first clone the repo, then use `file:///path/to/repo` 

You can also inline the password, ie `trufflehog https://username:$PASSWORD@gitprovider` but I don't suggest doing that bc it puts the password in the `.git/config` and can cause it to leak
