### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode characters ... character maps to <undefined>

### ISSUE THREAD

**Issue by mcmahonjohn** [dxa4481/truffleHog#36]
I saw for the previous issue #7 that you implemented a fix. When I tried ran truffleHog on the same repo, I got a very similar error. Unfortunately, my repo belongs to my employer so I cannot share it with you. Just figured it was worth posting in case anyone else has a similar problem.

```bash
Traceback (most recent call last):
  File "C:\Python\Python27\Scripts\trufflehog-script.py", line 9, in <module>
    load_entry_point('truffleHog==1.0.2', 'console_scripts', 'trufflehog')()
  File "c:\python\python27\lib\site-packages\truffleHog\truffleHog.py", line 20, in main
    output = find_strings(args.git_url, args.output_json)
  File "c:\python\python27\lib\site-packages\truffleHog\truffleHog.py", line 136, in find_strings
    print(printableDiff)
  File "c:\python\python27\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u2018' in position 1670: character maps to <undefined>
```

**Comment by dxa4481** [comment]
I think I fixed it. Reopen if it appears again.
