### ISSUE TITLE
special characters issue

### ISSUE THREAD

**Issue by verybigelephants** [dxa4481/truffleHog#63]
it seems there is some problem reading files with special characters in them, such as emoji codes like `\U0001f60a` and the truffleHog crashes

```
Traceback (most recent call last):                                                                                      
  File "c:\programs\python3\lib\runpy.py", line 184, in _run_module_as_main                                             
    "__main__", mod_spec)                                                                                               
  File "c:\programs\python3\lib\runpy.py", line 85, in _run_code                                                        
    exec(code, run_globals)                                                                                             
  File "C:\programs\python3\Scripts\trufflehog.exe\__main__.py", line 9, in <module>                                    
  File "c:\programs\python3\lib\site-packages\truffleHog\truffleHog.py", line 20, in main                               
    output = find_strings(args.git_url, args.output_json)                                                               
  File "c:\programs\python3\lib\site-packages\truffleHog\truffleHog.py", line 156, in find_strings                      
    print_results(printJson, commit_time, branch_name, prev_commit, printableDiff)                                      
  File "c:\programs\python3\lib\site-packages\truffleHog\truffleHog.py", line 89, in print_results                      
    print(printableDiff)                                                                                                
  File "c:\programs\python3\lib\encodings\cp437.py", line 19, in encode                                                 
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]                                                     
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f60a' in position 4615: character maps to <undefined> 
```

**Comment by dxa4481** [comment]
Can you give me a repo that errors? I think this is fixed, just want to make sure

**Comment by verybigelephants** [comment]
man that was a year ago, i have no idea now

**Comment by shoeper** [comment]
looks like it was an emoji: https://codepoints.net/U+1F60A?lang=de
