### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode characters ... character maps to <undefined>

### ISSUE THREAD

**Issue by gbrayut** [dxa4481/truffleHog#7]
Testing using a private Github repo (soon to be public) caused an error. It identified a few SHA1 hash strings in two different commits, then throws the following error:

```
Date: 2016-12-16 13:10:27
Branch: master
Commit: Nameserver overhaul (#17)

* go changes to support nameservers_from
... omitted ...

Traceback (most recent call last):
  File "truffleHog.py", line 108, in <module>
    find_strings(args.git_url)
  File "truffleHog.py", line 97, in find_strings
    print(printableDiff)
  File "c:\tools\python2\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode characters in position 1292428-1292443: character maps to <undefined>
```

Environment is Python 2.7 running on Windows 10 x64 bit. There are 50 changed files in the commit and it doesn't say which file caused the error, but my guess is it doesn't like one of the static.go files that has base64+GZip encoded JS/CSS files. See attached git patch for commit details.

[0001-Nameserver-overhaul-17.zip](https://github.com/dxa4481/truffleHog/files/681656/0001-Nameserver-overhaul-17.zip)

**Comment by mcmahonjohn** [comment]
I got something similar:
```
Traceback (most recent call last):
  File "truffleHog.py", line 130, in <module>
    project_path = find_strings(args.git_url)
  File "truffleHog.py", line 119, in find_strings
    print(printableDiff)
  File "C:\Python\Python27\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u2019' in position 43854: character maps to <undefined>
```

Python 2.7 on windows 10 64-bit.

**Comment by tommed** [comment]
Same here:
`[92mDate: 2017-05-18 09:35:32[0m
[92mBranch: master[0m
[92mCommit: refactoring & autocleanup
[0m
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\trufflehog.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\truffleHog\truffleHog.py", line 20, in main
    output = find_strings(args.git_url, args.output_json)
  File "c:\python27\lib\site-packages\truffleHog\truffleHog.py", line 136, in find_strings
    print(printableDiff)
  File "c:\python27\lib\encodings\cp850.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\ufeff' in position 19: character maps to <undefined>`
